name: AdaptedArmor
description: Rebalance Minecraft combat
version: ${pom.version}
main: net.snofox.minecraft.adaptedarmor.AdaptedArmor
author: SnoFox
website: https://www.snofox.net/
api-version: 1.13
depend: ["SnoLib"]
softdepend: []